DROP TABLE IF EXISTS program_exercises CASCADE;
DROP TABLE IF EXISTS programs CASCADE;
DROP TABLE IF EXISTS exercises CASCADE;
DROP TABLE IF EXISTS workouts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE workouts (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    title VARCHAR(100) NOT NULL,
    description TEXT
);
