name: CI - Test and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5004:5004
        options: --health-cmd="curl --silent --fail http://localhost:5004/health || exit 1"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: extrajoss
          POSTGRES_DB: gymapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Start backend
        run: |
          npm run build
          npm start &
        env:
          DATABASE_URL: postgres://postgres:extrajoss@database:5432/gymapp

      - name: Run tests
        run: npm run test

      - name: Generate coverage report
        run: npm run coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/lcov-report
