name: Run E2E Tests with Cypress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm ci

      - name: Start backend server
        run: |
          docker compose up -d backend

      - name: Wait for backend to start
        run: |
          while ! curl -s http://localhost:3000; do
            echo "Waiting for backend to start..."
            sleep 5
          done

      - name: Run Cypress tests
        run: |
          npx cypress run --spec 'cypress/e2e/settings.cy.ts'
