name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Wait for backend to start
        run: |
          echo "Waiting for backend to start..."
          while ! curl -s http://localhost:3000; do
            sleep 5
          done
          echo "Backend is up and running."

      - name: Install dependencies
        run: |
          npm install

      - name: Run Cypress E2E tests
        run: |
          npx cypress run --spec 'cypress/e2e/settings.cy.ts'
