name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display current directory and files
        run: |
          pwd  # Print current directory
          ls -al  # List all files in the current directory

      - name: Start backend and frontend
        run: |
          docker compose -f docker-compose.yml up -d backend frontend
